### ISSUE TITLE
Bump the lit version to lit@2 

### ISSUE THREAD

**Issue by jcgueriaud1** [F0rce/lit-ace#6]
Vaadin 23 is using lit@2.x instead of lit-html / lit-element.

Is it possible to bump lit version of the component for Vaadin 23? It will help to reduce the bundle size (only one lit version) and also the stability of the build.

Normally you only have to change:
- the package.json (remove lit-element and add lit)
    "lit": "ˆ2.1.0",

- and the import in lit-ace
```
import { LitElement, html, css } from "lit-element";
```
to
```
import { LitElement, html, css } from "lit";
```

Thanks

**Comment by F0rce** [comment]
Hello @jcgueriaud,

I didn't think of that and sure will implement it in a future version of my 3.x Ace. Thanks for showing this to me and I hope that there are no big breaking changes regarding the migration from lit-element to lit.

Will keep you updated, as soon as there is a new Ace Version released.

Have a great week,
David

**Comment by F0rce** [comment]
Hello @jcgueriaud1,

you were right. I only had to bump the dependencies in the package.json and change the import in lit-ace.js.

I will build a release for the Vaadin Directory later today. 

Thanks for showing me,
David
