### ISSUE TITLE
Unable to load ace-builds folder

### ISSUE THREAD

**Issue by wimspaargaren** [F0rce/lit-ace#8]
Hello, first of all super nice component, also I'm not a very experienced front-end developer, so I could just be doing something wrong.

**Describe the bug**
When I'm installing the component in my OpenWC typescript project I'm unable to resolve ace-builds folder.

**To Reproduce**
1. Create a OpenWC typescript application
2. Create `lit-ace` element
3. Error loading theme and mode.

**Expected behavior**
I would expect the theme and mode to resolve to `node_modules/@f0rce/ace-builds`. Instead it tries to find `ace-builds` in the root of the project (see screenshot).

I can work around the issue copying the `ace-builds` folder to the root of my project.

**Screenshots**

Error:
![Screenshot 2022-08-02 at 00 30 27](https://user-images.githubusercontent.com/2276589/182256417-fd4e2f9b-7c35-4595-9ffa-1ba5b52fc463.png)
`ace.js:883`:
![Screenshot 2022-08-02 at 00 36 32](https://user-images.githubusercontent.com/2276589/182257055-d0532012-2ea9-4428-beeb-f5a2b28757d6.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser: chrome

Thx in advance!

**Comment by F0rce** [comment]
Good morning @wimspaargaren,

yeah the so called basepath is wrong when using the webcomponent in a standalone environment. As stated in the readme, I created this webcomponent to fit and serve the needs of the Vaadin (Java Web Framework) Add-on I created. So you could use your workaround or select the instance of `lit-ace` and set the property `baseUrl` to your path. 

Hope that helps,
David

**Comment by wimspaargaren** [comment]
Hey @F0rce , thx for the swift response. Setting the baseUrl works like a charm 😄 

```HTML
    <lit-ace baseUrl="node_modules/@f0rce/ace-builds/src-min-noconflict" theme="monokai" mode="html"></lit-ace>
```

I'll close the issue 👍

**Comment by F0rce** [comment]
@wimspaargaren no worries :) have a great day
